### ISSUE TITLE
This week's action items

### ISSUE THREAD

**Issue by quarterback** [18F/osc-website-pa#26]
Convert each of these to an issue or tag an existing one.

- [ ] Meet with David (18F FE Engineer on Wed) (#17)
- [ ] Talk to 18F strategy chapter huddle about PA phase
- [ ] Domain mapping workshop exercise
- [ ] Discuss post-recommendations & next steps
- [ ] PM staffing/18F (ongoing, #17)
- [ ] OSC continues interviewing PO candidates (#22)
